name: test docker

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image in temporary directory
        run: |
          TEMP_DIR=$(mktemp -d)
          cp -r . "$TEMP_DIR"
          cd "$TEMP_DIR"
          docker build -t fizzbuzz-app .

      - name: Run tests inside Docker
        run: docker run --rm fizzbuzz-app python -m unittest discover tests
