name: Python Tests, Coverage, and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover
          coverage report
          coverage xml
          coverage html  # Pour générer un rapport HTML localement

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Mayesbrz/fizzbuzz-Efrei

      - name: Check code style with flake8
        run: flake8 main.py test/test_fizzbuzz.py

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image in temporary directory
        run: |
          TEMP_DIR=$(mktemp -d)
          cp -r . "$TEMP_DIR"
          cd "$TEMP_DIR"
          docker build -t fizzbuzz-app .

      - name: Run tests inside Docker
        run: docker run --rm fizzbuzz-app